AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: S3 Event Notification Configuration for Logo Detection

Parameters:
  EnvironmentName:
    Type: String
    Default: prod
    Description: Environment name (e.g., dev, staging, prod)
  
  S3BucketName:
    Type: String
    Default: logo-detection-file-storage-prod-942370948350
    Description: Name of the existing S3 bucket
  
  LambdaFunctionArn:
    Type: String
    Default: arn:aws:lambda:us-east-1:942370948350:function:s3-event-router-prod
    Description: ARN of the existing Lambda function

Resources:
  # Lambda Permission for S3 to invoke the router function
  S3EventRouterFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunctionArn
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceAccount: !Ref AWS::AccountId
      SourceArn: !Sub 'arn:aws:s3:::${S3BucketName}'

  # Custom Resource Lambda Function to configure S3 bucket notifications
  ApplyNotificationFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Path: /
      Policies:
        - PolicyName: S3BucketNotificationPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: AllowBucketNotification
                Effect: Allow
                Action: s3:PutBucketNotification
                Resource:
                  - !Sub 'arn:aws:s3:::${S3BucketName}'
                  - !Sub 'arn:aws:s3:::${S3BucketName}/*'

  ApplyBucketNotificationFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'apply-bucket-notification-${EnvironmentName}'
      Description: Custom resource to apply S3 bucket notification configuration
      Handler: index.handler
      Runtime: python3.9
      Role: !GetAtt ApplyNotificationFunctionRole.Arn
      Timeout: 240
      Code:
        ZipFile: |
          import boto3
          import logging
          import json
          import cfnresponse

          s3Client = boto3.client('s3')
          logger = logging.getLogger()
          logger.setLevel(logging.DEBUG)

          def addBucketNotification(bucketName, functionArn):
            notificationResponse = s3Client.put_bucket_notification_configuration(
              Bucket=bucketName,
              NotificationConfiguration={
                'LambdaFunctionConfigurations': [
                  {
                    'Id': 'S3ObjectCreatedEvent',
                    'LambdaFunctionArn': functionArn,
                    'Events': [
                      's3:ObjectCreated:*'
                    ],
                    'Filter': {
                      'Key': {
                        'FilterRules': [
                          {
                            'Name': 'prefix',
                            'Value': 'users/'
                          }
                        ]
                      }
                    }
                  },
                  {
                    'Id': 'S3ObjectRemovedEvent',
                    'LambdaFunctionArn': functionArn,
                    'Events': [
                      's3:ObjectRemoved:*'
                    ],
                    'Filter': {
                      'Key': {
                        'FilterRules': [
                          {
                            'Name': 'prefix',
                            'Value': 'users/'
                          }
                        ]
                      }
                    }
                  }
                ]
              }
            )
            return notificationResponse

          def removeBucketNotification(bucketName):
            try:
              notificationResponse = s3Client.put_bucket_notification_configuration(
                Bucket=bucketName,
                NotificationConfiguration={}
              )
              return notificationResponse
            except Exception as e:
              logger.warning('Failed to remove bucket notification: %s' % e)
              return None

          def create(properties, physical_id):
            bucketName = properties['S3Bucket']
            functionArn = properties['FunctionARN']
            response = addBucketNotification(bucketName, functionArn)
            logger.info('AddBucketNotification response: %s' % json.dumps(response, default=str))
            return cfnresponse.SUCCESS, physical_id

          def update(properties, physical_id):
            bucketName = properties['S3Bucket']
            functionArn = properties['FunctionARN']
            response = addBucketNotification(bucketName, functionArn)
            logger.info('UpdateBucketNotification response: %s' % json.dumps(response, default=str))
            return cfnresponse.SUCCESS, physical_id

          def delete(properties, physical_id):
            bucketName = properties['S3Bucket']
            response = removeBucketNotification(bucketName)
            logger.info('RemoveBucketNotification response: %s' % json.dumps(response, default=str))
            return cfnresponse.SUCCESS, physical_id

          def handler(event, context):
            logger.info('Received event: %s' % json.dumps(event))

            status = cfnresponse.FAILED
            new_physical_id = None

            try:
              properties = event.get('ResourceProperties')
              physical_id = event.get('PhysicalResourceId')

              status, new_physical_id = {
                'Create': create,
                'Update': update,
                'Delete': delete
              }.get(event['RequestType'], lambda x, y: (cfnresponse.FAILED, None))(properties, physical_id)
            except Exception as e:
              logger.error('Exception: %s' % e)
              status = cfnresponse.FAILED
            finally:
              cfnresponse.send(event, context, status, {}, new_physical_id)

  # Custom Resource to apply S3 bucket notification
  ApplyNotification:
    Type: Custom::ApplyNotification
    Properties:
      ServiceToken: !GetAtt ApplyBucketNotificationFunction.Arn
      S3Bucket: !Ref S3BucketName
      FunctionARN: !Ref LambdaFunctionArn
    DependsOn:
      - S3EventRouterFunctionPermission

Outputs:
  S3BucketNotificationConfigured:
    Description: 'S3 bucket notification configuration status'
    Value: 'Configured'
    
  LambdaPermissionArn:
    Description: 'Lambda permission ARN'
    Value: !Ref S3EventRouterFunctionPermission