AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple Logo Detection Processing System - Step 1

Parameters:
  EnvironmentName:
    Type: String
    Default: 'dev'
    Description: Environment name (dev, staging, prod)
  
  FileStorageBucketName:
    Type: String
    Description: S3 bucket name for file storage
    Default: 'logo-detection-file-storage'
    
  SupabaseUrl:
    Type: String
    Description: Supabase project URL
    Default: 'https://rttdivhngjwrhksfqjty.supabase.co' # TODO REMOVE 
    
  SupabaseServiceKey:
    Type: String
    Description: Supabase service role key
    Default: 'sb_secret_9my8NarLNjpEd3bH0ly99A_SfKOwsWi' # TODO REMOVE
    NoEcho: true

Globals:
  Function:
    Timeout: 60
    MemorySize: 256
    Runtime: nodejs22.x
    Environment:
      Variables:
        ENVIRONMENT: !Ref EnvironmentName
        SUPABASE_URL: !Ref SupabaseUrl
        SUPABASE_SERVICE_KEY: !Ref SupabaseServiceKey

Resources:
  # Bedrock Data Automation Project (SYNC type for synchronous API)
  BedrockDataAutomationProject:
    Type: AWS::Bedrock::DataAutomationProject
    Properties:
      ProjectName: !Sub 'logo-detection-sync-${EnvironmentName}'
      ProjectDescription: 'Synchronous logo detection project for image processing'
      ProjectType: 'SYNC'
      StandardOutputConfiguration:
        Image:
          Extraction:
            Category:
              State: 'ENABLED'
              Types:
                - 'LOGOS'
            BoundingBox:
              State: 'ENABLED'
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: logo-detection

  # S3 Bucket for file storage (notifications will be added post-deployment)
  FileStorageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${FileStorageBucketName}-${EnvironmentName}-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [GET, PUT, POST, DELETE, HEAD]
            AllowedOrigins: ['*']  # TODO You should restrict this to your domain in production
            ExposedHeaders: [ETag]
            MaxAge: 3000
      LifecycleConfiguration:
        Rules:
          - Id: DeleteIncompleteMultipartUploads
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1

  # S3 Event Router Lambda Function
  S3EventRouterFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 's3-event-router-${EnvironmentName}'
      CodeUri: functions/s3-event-router/
      Handler: index.handler
      Description: Routes S3 events to appropriate Step Functions based on file path
      Environment:
        Variables:
          IMAGE_PROCESSING_STATE_MACHINE_ARN: !Ref ImageProcessingStateMachine
          VIDEO_UPLOAD_STATE_MACHINE_ARN: !Ref VideoProcessingStateMachine
          FRAME_PROCESSING_STATE_MACHINE_ARN: ""
          RESULT_PROCESSING_STATE_MACHINE_ARN: ""
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - states:StartExecution
              Resource: 
                - !Ref ImageProcessingStateMachine
                - !Ref VideoProcessingStateMachine
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: '*'
    DependsOn:
      - ImageProcessingStateMachine
      - VideoProcessingStateMachine

  # File Status Updater Lambda Function
  FileStatusUpdaterFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'file-status-updater-${EnvironmentName}'
      CodeUri: functions/file-status-updater/
      Handler: index.handler
      Description: Updates file status in Supabase database
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: '*'

  # Job Status Updater Lambda Function
  JobStatusUpdaterFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'job-status-updater-${EnvironmentName}'
      CodeUri: functions/job-status-updater/
      Handler: index.handler
      Description: Creates and updates job records in Supabase database
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: '*'

  # FFmpeg Lambda Layer from Serverless Application Repository
  FFmpegLambdaLayer:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:145266761615:applications/ffmpeg-lambda-layer
        SemanticVersion: 1.0.0

  # Video Frame Extractor Lambda Function
  VideoFrameExtractorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'video-frame-extractor-${EnvironmentName}'
      CodeUri: functions/video-frame-extractor/
      Handler: index.handler
      Description: Extracts frames from video files using ffmpeg
      Timeout: 300  # 5 minutes for video processing
      MemorySize: 3008  # Max memory for better performance
      Layers:
        - !GetAtt FFmpegLambdaLayer.Outputs.LayerVersion
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
              Resource: 
                - !Sub '${FileStorageBucket.Arn}/*'
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: '*'

  # Frame Cleanup Lambda Function
  FrameCleanupFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'frame-cleanup-${EnvironmentName}'
      CodeUri: functions/frame-cleanup/
      Handler: index.handler
      Description: Deletes processed video frames from S3 to reduce storage costs
      Timeout: 30
      MemorySize: 256
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:ListBucket
              Resource: !GetAtt FileStorageBucket.Arn
            - Effect: Allow
              Action:
                - s3:DeleteObject
              Resource: 
                - !Sub '${FileStorageBucket.Arn}/users/*/frames/*'
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: '*'

  # Bedrock Image Processor Lambda Function
  BedrockImageProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'bedrock-image-processor-${EnvironmentName}'
      CodeUri: functions/bedrock-image-processor/
      Handler: index.handler
      Description: Processes images using Bedrock Data Automation and stores results
      Timeout: 10  # 10 seconds
      Environment:
        Variables:
          IMAGE_PROCESSING_QUEUE_URL: !Ref ImageProcessingQueue
          BEDROCK_PROJECT_ARN: !GetAtt BedrockDataAutomationProject.ProjectArn
          BEDROCK_PROFILE_ARN: 'arn:aws:bedrock:us-east-1:942370948350:data-automation-profile/us.data-automation-v1'
          FORCE_FAILURE: 'false'  # Set to 'true' to simulate failures for testing
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt ImageProcessingQueue.Arn
            BatchSize: 1  # Process one message at a time
            MaximumBatchingWindowInSeconds: 0
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeDataAutomation
                - bedrock-data-automation-runtime:InvokeDataAutomation
              Resource: '*'
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource: 
                - !Sub '${FileStorageBucket.Arn}/*'
            - Effect: Allow
              Action:
                - sqs:ReceiveMessage
                - sqs:DeleteMessage
                - sqs:GetQueueAttributes
              Resource: !GetAtt ImageProcessingQueue.Arn
            - Effect: Allow
              Action:
                - states:SendTaskSuccess
                - states:SendTaskFailure
              Resource: '*'
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: '*'

  # Dead Letter Queue for failed image processing jobs
  ImageProcessingDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub 'image-processing-dlq-${EnvironmentName}'
      MessageRetentionPeriod: 1209600  # 14 days

  # SQS Queue for image processing jobs
  ImageProcessingQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub 'image-processing-queue-${EnvironmentName}'
      VisibilityTimeout: 15  # 15 seconds (must be >= Lambda timeout)
      MessageRetentionPeriod: 1209600  # 14 days
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt ImageProcessingDLQ.Arn
        maxReceiveCount: 5

  # Image Processing Step Function (handles both upload and delete)
  ImageProcessingStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Sub 'image-processing-state-machine-${EnvironmentName}'
      DefinitionUri: statemachine/image-processing-workflow.asl.json
      DefinitionSubstitutions:
        FileStatusUpdaterFunctionArn: !GetAtt FileStatusUpdaterFunction.Arn
        JobStatusUpdaterFunctionArn: !GetAtt JobStatusUpdaterFunction.Arn
        ImageProcessingQueueUrl: !Ref ImageProcessingQueue
        BedrockImageProcessorFunctionArn: !GetAtt BedrockImageProcessorFunction.Arn
      Type: STANDARD
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref FileStatusUpdaterFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref JobStatusUpdaterFunction
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - sqs:SendMessage
                - sqs:GetQueueAttributes
              Resource: !GetAtt ImageProcessingQueue.Arn
            - Effect: Allow
              Action:
                - states:SendTaskSuccess
                - states:SendTaskFailure
              Resource: '*'

  # Video Processing Step Function
  VideoProcessingStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Sub 'video-processing-state-machine-${EnvironmentName}'
      DefinitionUri: statemachine/video-processing-workflow.asl.json
      DefinitionSubstitutions:
        FileStatusUpdaterFunctionArn: !GetAtt FileStatusUpdaterFunction.Arn
        JobStatusUpdaterFunctionArn: !GetAtt JobStatusUpdaterFunction.Arn
        VideoFrameExtractorFunctionArn: !GetAtt VideoFrameExtractorFunction.Arn
        FrameCleanupFunctionArn: !GetAtt FrameCleanupFunction.Arn
        ImageProcessingQueueUrl: !Ref ImageProcessingQueue
      Type: STANDARD
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref FileStatusUpdaterFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref JobStatusUpdaterFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref VideoFrameExtractorFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref FrameCleanupFunction
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - sqs:SendMessage
                - sqs:GetQueueAttributes
              Resource: !GetAtt ImageProcessingQueue.Arn
            - Effect: Allow
              Action:
                - states:SendTaskSuccess
                - states:SendTaskFailure
              Resource: '*'

  # CloudWatch Log Group for Step Functions
  StateMachineLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/stepfunctions/simple-state-machine-${EnvironmentName}'
      RetentionInDays: 14

  # IAM User for S3 access
  FileStorageUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub 'file-storage-user-${EnvironmentName}'
      Policies:
        - PolicyName: S3FileStorageAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # Allow listing bucket contents (needed for some operations)
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource: !GetAtt FileStorageBucket.Arn
                Condition:
                  StringLike:
                    's3:prefix': ['users/*']
              # Allow full access to user-specific prefixes
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:GetObjectVersion
                  - s3:DeleteObjectVersion
                Resource: !Sub '${FileStorageBucket.Arn}/users/*'
              # Allow generating presigned URLs
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: !Sub '${FileStorageBucket.Arn}/users/*'

  # Access Key for the IAM User
  FileStorageAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref FileStorageUser

Outputs:
  FileStorageBucketName:
    Description: 'S3 bucket name for file storage'
    Value: !Ref FileStorageBucket
    Export:
      Name: !Sub '${AWS::StackName}-FileStorageBucketName'

  FileStorageBucketArn:
    Description: 'S3 bucket ARN for file storage'
    Value: !GetAtt FileStorageBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-FileStorageBucketArn'

  AccessKeyId:
    Description: 'Access Key ID for S3 access'
    Value: !Ref FileStorageAccessKey
    Export:
      Name: !Sub '${AWS::StackName}-AccessKeyId'

  SecretAccessKey:
    Description: 'Secret Access Key for S3 access'
    Value: !GetAtt FileStorageAccessKey.SecretAccessKey
    Export:
      Name: !Sub '${AWS::StackName}-SecretAccessKey'

  Region:
    Description: 'AWS Region'
    Value: !Ref AWS::Region
    Export:
      Name: !Sub '${AWS::StackName}-Region'

  FileStatusUpdaterFunctionArn:
    Description: 'File Status Updater Function ARN'
    Value: !GetAtt FileStatusUpdaterFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-FileStatusUpdaterFunctionArn'

  JobStatusUpdaterFunctionArn:
    Description: 'Job Status Updater Function ARN'
    Value: !GetAtt JobStatusUpdaterFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-JobStatusUpdaterFunctionArn'

  ImageProcessingStateMachineArn:
    Description: 'Image Processing State Machine ARN'
    Value: !Ref ImageProcessingStateMachine
    Export:
      Name: !Sub '${AWS::StackName}-ImageProcessingStateMachineArn'

  S3EventRouterFunctionArn:
    Description: 'S3 Event Router Function ARN'
    Value: !GetAtt S3EventRouterFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-S3EventRouterFunctionArn'

  BedrockImageProcessorFunctionArn:
    Description: 'Bedrock Image Processor Function ARN'
    Value: !GetAtt BedrockImageProcessorFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-BedrockImageProcessorFunctionArn'

  ImageProcessingQueueUrl:
    Description: 'Image Processing SQS Queue URL'
    Value: !Ref ImageProcessingQueue
    Export:
      Name: !Sub '${AWS::StackName}-ImageProcessingQueueUrl'

  ImageProcessingQueueArn:
    Description: 'Image Processing SQS Queue ARN'
    Value: !GetAtt ImageProcessingQueue.Arn
    Export:
      Name: !Sub '${AWS::StackName}-ImageProcessingQueueArn'

  ImageProcessingDLQUrl:
    Description: 'Image Processing Dead Letter Queue URL'
    Value: !Ref ImageProcessingDLQ
    Export:
      Name: !Sub '${AWS::StackName}-ImageProcessingDLQUrl'

  ImageProcessingDLQArn:
    Description: 'Image Processing Dead Letter Queue ARN'
    Value: !GetAtt ImageProcessingDLQ.Arn
    Export:
      Name: !Sub '${AWS::StackName}-ImageProcessingDLQArn'

  VideoFrameExtractorFunctionArn:
    Description: 'Video Frame Extractor Function ARN'
    Value: !GetAtt VideoFrameExtractorFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-VideoFrameExtractorFunctionArn'

  VideoProcessingStateMachineArn:
    Description: 'Video Processing State Machine ARN'
    Value: !Ref VideoProcessingStateMachine
    Export:
      Name: !Sub '${AWS::StackName}-VideoProcessingStateMachineArn'
