AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 File Storage Infrastructure with User-based Access Control'

Parameters:
  EnvironmentName:
    Type: String
    Default: 'dev'
    Description: Environment name (dev, staging, prod)
  
  FileStorageBucketName:
    Type: String
    Description: S3 bucket name for file storage
    Default: 'logo-detection-file-storage'

Resources:
  # S3 Bucket for file storage
  FileStorageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${FileStorageBucketName}-${EnvironmentName}-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            AllowedOrigins:
              - '*'  # In production, restrict to your domain
            ExposedHeaders:
              - ETag
            MaxAge: 3000
      LifecycleConfiguration:
        Rules:
          - Id: DeleteIncompleteMultipartUploads
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30

  # CloudWatch Log Group for S3 events
  FileStorageLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/s3/${FileStorageBucketName}-${EnvironmentName}'
      RetentionInDays: 30

  # IAM User for application access to S3
  FileStorageUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub 'file-storage-user-${EnvironmentName}'
      Policies:
        - PolicyName: S3FileStorageAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # Allow listing bucket contents (needed for some operations)
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource: !GetAtt FileStorageBucket.Arn
                Condition:
                  StringLike:
                    's3:prefix': 
                      - 'users/*'
              # Allow full access to user-specific prefixes
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:GetObjectVersion
                  - s3:DeleteObjectVersion
                Resource: !Sub '${FileStorageBucket.Arn}/users/*'
              # Allow generating presigned URLs
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: !Sub '${FileStorageBucket.Arn}/users/*'

  # Access Key for the IAM User
  FileStorageAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref FileStorageUser

  # CloudWatch Alarms for monitoring
  BucketSizeAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'S3-BucketSize-${EnvironmentName}'
      AlarmDescription: 'Alert when bucket size exceeds threshold'
      MetricName: BucketSizeBytes
      Namespace: AWS/S3
      Statistic: Average
      Period: 86400  # 24 hours
      EvaluationPeriods: 1
      Threshold: 10737418240  # 10GB in bytes
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: BucketName
          Value: !Ref FileStorageBucket
        - Name: StorageType
          Value: StandardStorage

  NumberOfObjectsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'S3-NumberOfObjects-${EnvironmentName}'
      AlarmDescription: 'Alert when number of objects exceeds threshold'
      MetricName: NumberOfObjects
      Namespace: AWS/S3
      Statistic: Average
      Period: 86400  # 24 hours
      EvaluationPeriods: 1
      Threshold: 100000  # 100k objects
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: BucketName
          Value: !Ref FileStorageBucket
        - Name: StorageType
          Value: AllStorageTypes

Outputs:
  BucketName:
    Description: 'S3 bucket name for file storage'
    Value: !Ref FileStorageBucket
    Export:
      Name: !Sub '${AWS::StackName}-BucketName'

  BucketArn:
    Description: 'S3 bucket ARN'
    Value: !GetAtt FileStorageBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-BucketArn'

  BucketDomainName:
    Description: 'S3 bucket domain name'
    Value: !GetAtt FileStorageBucket.DomainName
    Export:
      Name: !Sub '${AWS::StackName}-BucketDomainName'

  AccessKeyId:
    Description: 'Access Key ID for S3 access'
    Value: !Ref FileStorageAccessKey
    Export:
      Name: !Sub '${AWS::StackName}-AccessKeyId'

  SecretAccessKey:
    Description: 'Secret Access Key for S3 access (store securely)'
    Value: !GetAtt FileStorageAccessKey.SecretAccessKey
    Export:
      Name: !Sub '${AWS::StackName}-SecretAccessKey'

  Region:
    Description: 'AWS Region'
    Value: !Ref AWS::Region
    Export:
      Name: !Sub '${AWS::StackName}-Region'