AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: S3 File Storage with Event Processing Pipeline

Parameters:
  EnvironmentName:
    Type: String
    Default: 'dev'
    Description: Environment name (dev, staging, prod)
  
  FileStorageBucketName:
    Type: String
    Description: S3 bucket name for file storage
    Default: 'logo-detection-file-storage'
  
  SupabaseUrl:
    Type: String
    Description: Supabase project URL
    NoEcho: true

  SupabaseServiceKey:
    Type: String
    Description: Supabase service role key
    NoEcho: true

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Runtime: nodejs18.x
    Environment:
      Variables:
        SUPABASE_URL: !Ref SupabaseUrl
        SUPABASE_SERVICE_KEY: !Ref SupabaseServiceKey
        ENVIRONMENT: !Ref EnvironmentName

Resources:
  # Dead Letter Queue for failed messages
  FileProcessingDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub 'file-processing-dlq-${EnvironmentName}'
      MessageRetentionPeriod: 1209600  # 14 days

  # SQS Queue for S3 object creation events
  FileProcessingQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub 'file-processing-queue-${EnvironmentName}'
      VisibilityTimeout: 300  # 5 minutes
      MessageRetentionPeriod: 1209600  # 14 days
      ReceiveMessageWaitTimeSeconds: 20  # Long polling
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt FileProcessingDLQ.Arn
        maxReceiveCount: 3

  # S3 Bucket for file storage
  FileStorageBucket:
    Type: AWS::S3::Bucket
    DependsOn: FileProcessingQueuePolicy
    Properties:
      BucketName: !Sub '${FileStorageBucketName}-${EnvironmentName}-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            AllowedOrigins:
              - '*'  # In production, restrict to your domain
            ExposedHeaders:
              - ETag
            MaxAge: 3000
      LifecycleConfiguration:
        Rules:
          - Id: DeleteIncompleteMultipartUploads
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
      NotificationConfiguration:
        QueueConfigurations:
          - Event: s3:ObjectCreated:*
            Queue: !GetAtt FileProcessingQueue.Arn
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: users/
          - Event: s3:ObjectRemoved:*
            Queue: !GetAtt FileProcessingQueue.Arn
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: users/

  # SQS Queue Policy to allow S3 to send messages
  FileProcessingQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref FileProcessingQueue
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action:
              - sqs:SendMessage
            Resource: !GetAtt FileProcessingQueue.Arn
            Condition:
              ArnLike:
                'aws:SourceArn': !Sub 'arn:aws:s3:::${FileStorageBucketName}-${EnvironmentName}-${AWS::AccountId}'

  # Lambda function to process S3 events from SQS
  FileStatusUpdaterFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'file-status-updater-${EnvironmentName}'
      CodeUri: src/
      Handler: index.handler
      Description: Updates file status in Supabase based on S3 events from SQS
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt FileProcessingQueue.Arn
            BatchSize: 10
            MaximumBatchingWindowInSeconds: 5
      Policies:
        - SQSPollerPolicy:
            QueueName: !GetAtt FileProcessingQueue.QueueName
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: '*'

  # IAM User for application access to S3 and SQS
  FileStorageUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub 'file-storage-user-${EnvironmentName}'
      Policies:
        - PolicyName: S3FileStorageAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # Allow listing bucket contents (needed for some operations)
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource: !GetAtt FileStorageBucket.Arn
                Condition:
                  StringLike:
                    's3:prefix': 
                      - 'users/*'
              # Allow full access to user-specific prefixes
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:GetObjectVersion
                  - s3:DeleteObjectVersion
                Resource: !Sub '${FileStorageBucket.Arn}/users/*'
              # Allow generating presigned URLs
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: !Sub '${FileStorageBucket.Arn}/users/*'
        - PolicyName: SQSFileProcessingAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # Allow receiving and deleting messages from the processing queue
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                  - sqs:GetQueueUrl
                Resource: 
                  - !GetAtt FileProcessingQueue.Arn
              # Allow reading DLQ for monitoring/debugging
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:GetQueueAttributes
                  - sqs:GetQueueUrl
                Resource: 
                  - !GetAtt FileProcessingDLQ.Arn

  # Access Key for the IAM User
  FileStorageAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref FileStorageUser

  # CloudWatch Alarms for monitoring
  BucketSizeAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'S3-BucketSize-${EnvironmentName}'
      AlarmDescription: 'Alert when bucket size exceeds threshold'
      MetricName: BucketSizeBytes
      Namespace: AWS/S3
      Statistic: Average
      Period: 86400  # 24 hours
      EvaluationPeriods: 1
      Threshold: 10737418240  # 10GB in bytes
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: BucketName
          Value: !Ref FileStorageBucket
        - Name: StorageType
          Value: StandardStorage

  NumberOfObjectsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'S3-NumberOfObjects-${EnvironmentName}'
      AlarmDescription: 'Alert when number of objects exceeds threshold'
      MetricName: NumberOfObjects
      Namespace: AWS/S3
      Statistic: Average
      Period: 86400  # 24 hours
      EvaluationPeriods: 1
      Threshold: 100000  # 100k objects
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: BucketName
          Value: !Ref FileStorageBucket
        - Name: StorageType
          Value: AllStorageTypes

  # SQS DLQ Alarm
  DLQMessagesAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'SQS-DLQ-Messages-${EnvironmentName}'
      AlarmDescription: 'Alert when messages appear in DLQ'
      MetricName: ApproximateNumberOfVisibleMessages
      Namespace: AWS/SQS
      Statistic: Sum
      Period: 300  # 5 minutes
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: QueueName
          Value: !GetAtt FileProcessingDLQ.QueueName

  # SQS Queue Depth Alarm
  QueueDepthAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'SQS-QueueDepth-${EnvironmentName}'
      AlarmDescription: 'Alert when queue depth is high'
      MetricName: ApproximateNumberOfVisibleMessages
      Namespace: AWS/SQS
      Statistic: Average
      Period: 300  # 5 minutes
      EvaluationPeriods: 2
      Threshold: 100
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: QueueName
          Value: !GetAtt FileProcessingQueue.QueueName

  # Lambda Error Alarm
  LambdaErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'FileStatus-Lambda-Errors-${EnvironmentName}'
      AlarmDescription: 'Alert on Lambda function errors'
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref FileStatusUpdaterFunction

  LambdaDurationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'FileStatus-Lambda-Duration-${EnvironmentName}'
      AlarmDescription: 'Alert on Lambda function high duration'
      MetricName: Duration
      Namespace: AWS/Lambda
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 10000  # 10 seconds
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref FileStatusUpdaterFunction

Outputs:
  BucketName:
    Description: 'S3 bucket name for file storage'
    Value: !Ref FileStorageBucket
    Export:
      Name: !Sub '${AWS::StackName}-BucketName'

  BucketArn:
    Description: 'S3 bucket ARN'
    Value: !GetAtt FileStorageBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-BucketArn'

  BucketDomainName:
    Description: 'S3 bucket domain name'
    Value: !GetAtt FileStorageBucket.DomainName
    Export:
      Name: !Sub '${AWS::StackName}-BucketDomainName'

  QueueUrl:
    Description: 'SQS Queue URL for file processing'
    Value: !Ref FileProcessingQueue
    Export:
      Name: !Sub '${AWS::StackName}-QueueUrl'

  QueueArn:
    Description: 'SQS Queue ARN'
    Value: !GetAtt FileProcessingQueue.Arn
    Export:
      Name: !Sub '${AWS::StackName}-QueueArn'

  DLQUrl:
    Description: 'Dead Letter Queue URL'
    Value: !Ref FileProcessingDLQ
    Export:
      Name: !Sub '${AWS::StackName}-DLQUrl'

  DLQArn:
    Description: 'Dead Letter Queue ARN'
    Value: !GetAtt FileProcessingDLQ.Arn
    Export:
      Name: !Sub '${AWS::StackName}-DLQArn'

  AccessKeyId:
    Description: 'Access Key ID for S3 access'
    Value: !Ref FileStorageAccessKey
    Export:
      Name: !Sub '${AWS::StackName}-AccessKeyId'

  SecretAccessKey:
    Description: 'Secret Access Key for S3 access (store securely)'
    Value: !GetAtt FileStorageAccessKey.SecretAccessKey
    Export:
      Name: !Sub '${AWS::StackName}-SecretAccessKey'

  Region:
    Description: 'AWS Region'
    Value: !Ref AWS::Region
    Export:
      Name: !Sub '${AWS::StackName}-Region'

  FunctionArn:
    Description: File Status Updater Lambda Function ARN
    Value: !GetAtt FileStatusUpdaterFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-FunctionArn'
  
  FunctionName:
    Description: File Status Updater Lambda Function Name
    Value: !Ref FileStatusUpdaterFunction
    Export:
      Name: !Sub '${AWS::StackName}-FunctionName'